# Generated by Django 5.0.7 on 2024-09-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['date'], 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
